// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXxBR1QKOSP5qk2t7qswNGvWCKxSbhqo4',
    appId: '1:248739298610:web:f4d5ab47ea025105c02b2b',
    messagingSenderId: '248739298610',
    projectId: 'kak-ty',
    authDomain: 'kak-ty.firebaseapp.com',
    storageBucket: 'kak-ty.firebasestorage.app',
    measurementId: 'G-PCMYVE4TQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyLwIEWl090L97PB5Ix098P8Oj8PNrEA',
    appId: '1:248739298610:android:bcd608fc7bb39e1dc02b2b',
    messagingSenderId: '248739298610',
    projectId: 'kak-ty',
    storageBucket: 'kak-ty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYJD-rjfGk2NLi4qDKs7CbBg3rICVnDQ',
    appId: '1:248739298610:ios:81f359f08892ae4fc02b2b',
    messagingSenderId: '248739298610',
    projectId: 'kak-ty',
    storageBucket: 'kak-ty.firebasestorage.app',
    iosBundleId: 'com.example.emotionGptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLYJD-rjfGk2NLi4qDKs7CbBg3rICVnDQ',
    appId: '1:248739298610:ios:81f359f08892ae4fc02b2b',
    messagingSenderId: '248739298610',
    projectId: 'kak-ty',
    storageBucket: 'kak-ty.firebasestorage.app',
    iosBundleId: 'com.example.emotionGptApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXxBR1QKOSP5qk2t7qswNGvWCKxSbhqo4',
    appId: '1:248739298610:web:728f56a08c91c3bbc02b2b',
    messagingSenderId: '248739298610',
    projectId: 'kak-ty',
    authDomain: 'kak-ty.firebaseapp.com',
    storageBucket: 'kak-ty.firebasestorage.app',
    measurementId: 'G-1EVJ8XWDK1',
  );
}
